//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIUsers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favoriteteamsuser
    {
        public int idFavoriteTeamsUser { get; set; }
        public int idUser { get; set; }
        public int idTeam { get; set; }
        public int idChampionship { get; set; }
    
        public virtual user user { get; set; }
    }
}
